-- Si ya creaste la tabla de la version anterior, por favor BORRALA antes de correr esto:
DROP TABLE IF EXISTS meka_arqueos_caja;

CREATE TABLE meka_arqueos_caja (
  id bigint generated by default as identity primary key,
  tenant_id uuid references meka_tenants(id) not null,
  estado text not null check (estado in ('abierta', 'cerrada')) default 'abierta',
  fecha_apertura timestamp with time zone default now() not null,
  fecha_cierre timestamp with time zone,
  
  -- Bases Iniciales
  apertura_efectivo numeric default 0 not null,
  apertura_tarjeta_debito numeric default 0 not null,
  apertura_tarjeta_credito numeric default 0 not null,
  apertura_nequi numeric default 0 not null,
  apertura_daviplata numeric default 0 not null,
  
  -- Ventas (Sistema)
  ventas_efectivo numeric default 0 not null,
  ventas_tarjeta_debito numeric default 0 not null,
  ventas_tarjeta_credito numeric default 0 not null,
  ventas_nequi numeric default 0 not null,
  ventas_daviplata numeric default 0 not null,
  
  -- Cierre (Físico declarado por el usuario)
  cierre_efectivo numeric default 0 not null,
  cierre_tarjeta_debito numeric default 0 not null,
  cierre_tarjeta_credito numeric default 0 not null,
  cierre_nequi numeric default 0 not null,
  cierre_daviplata numeric default 0 not null,

  diferencia_total numeric default 0 not null,
  observaciones text,
  usuario_id uuid not null
);

ALTER TABLE meka_arqueos_caja ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Los usuarios pueden ver cajas de su tenant" ON meka_arqueos_caja
  FOR SELECT USING (auth.uid() IN (
    SELECT user_id FROM meka_user_profiles WHERE tenant_id = meka_arqueos_caja.tenant_id
  ));

CREATE POLICY "Los usuarios pueden insertar cajas de su tenant" ON meka_arqueos_caja
  FOR INSERT WITH CHECK (auth.uid() IN (
    SELECT user_id FROM meka_user_profiles WHERE tenant_id = meka_arqueos_caja.tenant_id
  ));

CREATE POLICY "Los usuarios pueden actualizar cajas de su tenant" ON meka_arqueos_caja
  FOR UPDATE USING (auth.uid() IN (
    SELECT user_id FROM meka_user_profiles WHERE tenant_id = meka_arqueos_caja.tenant_id
  ));
